# Generated by Django 5.0.6 on 2024-07-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Activo?')),
                ('orientation', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], default='H', max_length=1)),
                ('numberparq', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('floor_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='floors.floors', verbose_name='N° Piso')),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Filas',
            },
        ),
    ]
