# Generated by Django 5.0.6 on 2024-07-04 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0003_rename_floor_id_rows_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='floor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='floors.floors', verbose_name='N° Piso'),
        ),
    ]
