# Generated by Django 5.0.6 on 2024-07-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0006_alter_rows_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='floors.floors', verbose_name='N° Piso'),
        ),
        migrations.AlterField(
            model_name='rows',
            name='numberparq',
            field=models.IntegerField(verbose_name='N° Parqueaderos'),
        ),
    ]
