# Generated by Django 5.0.6 on 2024-07-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0008_alter_rows_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rows',
            name='numberrows',
            field=models.IntegerField(default=0, verbose_name='N° Filas'),
        ),
    ]
