# Generated by Django 5.0.6 on 2024-07-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0009_rows_numberrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='numberparq',
            field=models.IntegerField(default=0, verbose_name='N° Parqueaderos'),
        ),
    ]
