# Generated by Django 5.0.6 on 2024-07-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0011_alter_rows_orientation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rows',
            new_name='ParkingLots',
        ),
        migrations.AlterModelOptions(
            name='parkinglots',
            options={'verbose_name': 'Estacionamiento', 'verbose_name_plural': 'Estacionamientos'},
        ),
    ]
