# Generated by Django 5.0.6 on 2024-07-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0012_rename_rows_parkinglots_alter_parkinglots_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Activo?')),
                ('busy', models.BooleanField(default=False, verbose_name='Ocupado?')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
            },
        ),
    ]
