# Generated by Django 5.0.6 on 2024-07-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0016_alter_spaces_parkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='spaces',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado'),
        ),
    ]
