# Generated by Django 5.0.6 on 2024-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0017_spaces_created_at_spaces_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='plate',
            field=models.CharField(default='', max_length=15, verbose_name='Placa'),
        ),
    ]
