# Generated by Django 5.0.6 on 2024-07-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0018_spaces_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Placa'),
        ),
    ]
