# Generated by Django 5.0.6 on 2024-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0022_alter_spaces_exit_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='exit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
