# Generated by Django 5.0.6 on 2024-07-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0023_alter_spaces_exit_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaces',
            name='exit_at',
        ),
    ]
