# Generated by Django 5.0.6 on 2024-07-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0024_remove_spaces_exit_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaces',
            name='income_at',
        ),
    ]
