# Generated by Django 5.0.6 on 2024-07-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0026_spaces_exit_at_spaces_income_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='income_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha ingreso'),
        ),
    ]
