# Generated by Django 5.0.6 on 2024-07-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0027_alter_spaces_income_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, default='', max_length=15, verbose_name='Placa')),
                ('income_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha ingreso')),
                ('exit_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha salida')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='floors.spaces', verbose_name='Espacio')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
