# Generated by Django 5.0.6 on 2024-07-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0028_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
    ]
